name: Runs a part of functional tests

on:
  pull_request:
  schedule:
  - cron:  '0 0 * * *' 
   

jobs:
  build:

    runs-on: macOS-10.14

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Set up NodeJS 10
      uses: actions/setup-node@v1
      with:
        node-version: 10.16.3
    - name: Set up appium beta, mjpeg-consumer
      run: npm install appium@beta mjpeg-consumer
    - name: Xcode Select 10.3
      run: sudo xcode-select -s /Applications/Xcode_10.3.app/Contents/Developer
    - name: Runs appium server
      run: appium --log-timestamp --log-no-colors --relaxed-security > appiumlog.txt
    - name: Run tests
      run: bundle exec rake test:func:ios TESTS=test/functional/ios/driver_test.rb
